@url = http://localhost:8000
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3ODIyMTgzNTAsImV4cCI6MTc4MjIyMTk1MCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidGVzdDZAdGVzdC5jb20ifQ.ah3O6JHRle6x_oDTLUxSs1mZf7L7KGzbXiKrvIbV85y_xAbEKlm87pH218LbNALU7pnDItLrvPm_0oDeL-d6QP7Gdf7OpzNSRKkJVkZZCfS_amR-jU8qDCEu7lrbwQR2NP_zsjiwTFBYQZ7jLf6PBUSRWNa0j2H7m1r_Ht0H5DD5pKz9sm7cTj97FIVzJ3NSpBEE7LCmeCCFcxN0ma0fpaxNcHbyR9kLjPqC6STr6KDGVP7ZgRXSwkKjkMXGY8Wa-4D-cWptegUmj0cR09bvDJ-XUqMh0Vak8-bMLfvcpoBhmCVSGvB6Msq6mF8kffUZAwQ75oP5nv7rXVz4xjCMtyvqczYQnp15OSluVRy18sxDqI2BT_aQQzGmeS2PDQi7c0LSzN3wJQ5F5AzGqMYT3OKJZzTvLbbznqGs5PxvK8r19JZwsovlBQ6zW_IOHJ5W54t7pUZQY2RocryciWT1uDPej9hwX22Vwb76bR9nW_ujw0Aed5SqwJdWYL2S5dNCDPBQsH6lia_Yb5_mNW1ED4dcAv7ZZaJVC-y8UaXwoby3ZA3yz9g7jS5Qr6LROH1S-pn-OQ_vnaI5rs7TZwNBSmZpepRaHsSxH2j88YEGjq9iyi96vGnGGqukC3zbuXy8ZyX6jzdgDtIA5BnONb_nrrSNiYtwAyWTCZy-E2Qglhs
#------------------ User -----------------
### Create user
POST {{url}}/api/register
Content-Type: application/json
Accept: application/json

{
  "email": "test6@test.com",
  "password": "123456"
}

### Login user
POST {{url}}/api/login
Content-Type: application/json
Accept: application/json

{
  "email": "test6@test.com",
  "password": "123456"
}

#------------------ Task -----------------
### Create Task
POST {{url}}/api/task
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "title": "Create Symfony project with SQRS architecture"
}

### GET Task List
GET {{url}}/api/tasks
# GET {{url}}/api/tasks?assigneeId=&limit=10&offset=0
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

### Assign Task
PUT {{url}}/api/task/assignee
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "taskId": 11,
  "userEmail": "newtest@test.com"
}

### Start Task
POST {{url}}/api/task/start
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "taskId": 12
}

### Complete Task
POST {{url}}/api/task/complete
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "taskId": 14
}

### Suggest Subtasks via OpenAI
POST {{url}}/api/task/suggest-subtasks
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "taskId": 13
}