@url = http://localhost:8000
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3ODE0MzYxNjksImV4cCI6MTc4MTQzOTc2OSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidGVzdDZAdGVzdC5jb20ifQ.PRIHEhIc76DGTIzjI3p_Kz-5EZH8FVEGc-2X43taLdX9AreXiyw5UklLVMvJ7rCBtZIaXkRo7ERxY6bcKBZxlNo3absVlnZGXSTzwdtnCb1DDt2t8d4kV7X78eB2iUSrfE7zbZvsD-GvNbWPGsE1_Q_6kuah-Py-PQLbBYu2mjhrQQ_c_YNqBpbir0xpjJfoquaVDYebo1_DDo07LVSAj7eL7kqwlpjS21e-nZjxT8RUBzIaAhmGdQXkxG03_e_Kub__DO7_wJB8fMhzJOhcPqt3-mrRU-Il01k6jUCnTvZZ4Z9qja5ainRgNrGJ2F81KWAYQzqBVZFlSDsuHwVG2mhTSFETmGlVcorcZd3TASffs81PaGPi9fIqtUO6Yj5O9xGD2ugUcu1dCy2D6OUp3Gc0DdVDdUVRuwPBinGgsbX3E_Ea3hVdhH7qA0aaQ7kM5gaDX3JVc4FIZbvabXCYBCXjZaZZ8KGz8I4tnYIX4lCZEAN32bJBtz2EKWPaAVXg_50VqGcsdqxEv1aSNZ11t8iijhye_7FXUgU1iRmz3WOwXtgii2QvvRLMNTy5Px_pMoYyHazUbl9cUfpHX_W7feOgaA9YRasbJd3aXLOON_YqwecHiNLI42IXH93tFpYSsThh4xFJwhcTRrGBiseDC-NQEboKruFVIv27S2OPzg0
#------------------ User -----------------
### Create user
POST {{url}}/api/register
Content-Type: application/json
Accept: application/json

{
  "email": "test6@test.com",
  "password": "123456"
}

### Login user
POST {{url}}/api/login
Content-Type: application/json
Accept: application/json

{
  "email": "test6@test.com",
  "password": "123456"
}

#------------------ Task -----------------
### Create Task
POST {{url}}/api/task
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "title": "Create Symfony project with SQRS architecture"
}

### GET Task List
GET {{url}}/api/tasks
# GET {{url}}/api/tasks?assigneeId=&limit=10&offset=0
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

### Assign Task
PUT {{url}}/api/task/assignee
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "taskId": 11,
  "userEmail": "newtest@test.com"
}

### Start Task
POST {{url}}/api/task/start
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "taskId": 12
}

### Complete Task
POST {{url}}/api/task/complete
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "taskId": 12
}

### Suggest Subtasks via OpenAI
POST {{url}}/api/task/suggest-subtasks
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "taskId": 13
}