@url = http://localhost:8000
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3Nzk3Nzk4NTIsImV4cCI6MTc3OTc4MzQ1Miwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidGVzdEB0ZXN0LmNvbSJ9.o99EaUy_6NJm75-DmY9vfzr42jV5GQjWbpXwZ_-JbqEKsv3PYXp69WFyBJtMBu8EspqaYUh8fXk5LOeHZNwigFSJCYzLZPRriPA1x9tLY9KNbV3D6qbWLeoa-rXu6XjBrf_uWuGBXazwZgDeffAcpsZQwkjal6yQhOG7uqfSgOC2Er7hen-L5AqG0x_ZdQr4ab91ZaJtuJtgFlOwhFPRDAxzPChm2hnrjz6pdssX7g3nkk45vrFTbvI4sJFXq5sjcynmC1_yRx2g81sdZSMWrF9tQ1KfhhdajZp0P9wiZ012SV5zgZfnfKuQGLHD6-7cDhjMLkW2TfGbj_DTqNKzEjwbj9xy0UE2pIpicGWUYnDJPkyRuJya76ORqP1WI7yFYq9kIaNBrUs2ERWX88nszr8TTRddZqTBRNWCHxJe8OKLnYneLVdADJ-00BXDn1Ct_Xk9GVYM_FcmW5db3Q2VG6UOV6HTEscc98HcTnBbBTamHqLzTCLOj4vgSViW2kEFp69OYTDMrtaNqb6vbXrl-R6ZOSna8sTPdDJ3U-eEIltBFV6oL0JfCeoWUo_BYjYfQh5LiQA3GpRn4Ul28iqts0Gw_IYQTGzd8fq4T-CdxAUKpUWHOjDFAfuKYX4-i36O3RflJBIbFfA1aUvuBCEaCTWxRr-3wAXriixcJK0pIls
#------------------ User -----------------
### Create user
POST {{url}}/api/register
Content-Type: application/json
Accept: application/json

{
  "email": "test6@test.com",
  "password": "123456"
}

### Login user
POST {{url}}/api/login
Content-Type: application/json
Accept: application/json

{
  "email": "test@test.com",
  "password": "123456"
}

#------------------ Task -----------------
### Create Task
POST {{url}}/api/task
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "title": "Create Symfony project with DDD architecture"
}

### GET Task List
GET {{url}}/api/tasks
# GET {{url}}/api/tasks?assigneeId=&limit=10&offset=0
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

### Assign Task
PUT {{url}}/api/task/assignee
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "taskId": 8,
  "userEmail": "newtest@test.com"
}

### Start Task
POST {{url}}/api/task/start
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "taskId": 9
}

### Complete Task
POST {{url}}/api/task/complete
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "taskId": 8
}

### Suggest Subtasks via OpenAI
POST {{url}}/api/task/suggest-subtasks
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "taskId": 12
}