# config/services.yaml

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Main registration
    App\:
        resource: '../src/'
        autowire: true
        autoconfigure: true
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Registering controllers explicitly
    App\Infrastructure\Controller\:
        resource: '../src/Infrastructure/Controller/'
        tags: ['controller.service_arguments']

    # Binding interfaces to implementations
    App\Domain\User\UserRepositoryInterface:
        alias: App\Infrastructure\Repository\DoctrineUserRepository

    App\Domain\Task\TaskRepositoryInterface:
        alias: App\Infrastructure\Repository\DoctrineTaskRepository

    OpenAI\Client:
        factory: ['OpenAI', 'client']
        arguments:
            $apiKey: '%env(OPENAI_API_KEY)%'

    monolog.formatter.command:
        class: Monolog\Formatter\LineFormatter
        arguments:
            # $format: "[%%datetime%%] %%level_name%%: %%message%%\n"
            $format: "%%message%%\n"